### ISSUE TITLE
Change in recognition of re-bound buttons

### ISSUE THREAD

**Issue by pallaswept** [taj-ny/InputActions#127]
Hi taj-ny

I have my mouse side buttons re-bound to ctrl and shift:

![Image](https://github.com/user-attachments/assets/c5436cfa-b0f3-40b1-a036-40bcc27bad04)

I had these:

```
    - type: stroke
      strokes: [ 'ZF4AtAAFZAA=' ] # Up-left
      mouse_buttons: [ forward, right ]
      conditions:
        - $window_fullscreen == false
    
      actions:
        - input:
          - keyboard: [ leftctrl+q ] # Quit


    - type: stroke
      strokes: [ 'ZF4AtAAFZAA=' ] # Up-left
      mouse_buttons: [ right ]
      conditions:
        - $window_fullscreen == false
        - $keyboard_modifiers == [ ctrl ]
    
      actions:
        - input:
          - keyboard: [ leftctrl+q ] # Quit
```

So I could use the real ctrl key, or the 'forward' mouse button, with my stroke gesture.

I noticed that with the re-bound 'forward' button, the gesture here was not working after upgrading from a7f95e8 to a5eb9f8 .

I commented out the first of these gestures, and the bottom one now works, but this struck me as odd, and I thought I should mention it. It seems like it's not aware of the input at the compositor any more, only after that?
