### ISSUE TITLE
Failed to load configuration - but still seems to work?

### ISSUE THREAD

**Issue by pallaswept** [taj-ny/InputActions#128]
After upgrading from https://github.com/taj-ny/InputActions/commit/a7f95e822b347d1e3483475ad7869628621c2adc to https://github.com/taj-ny/InputActions/commit/a5eb9f8ecd2d36e1b5affaa7659a1dc8a1bd28f9 I am seeing the following error in my journal when the configuration changes:

```
Jun 24 10:12:16 Pallas kwin_wayland[2748]: inputactions: Failed to load configuration: invalid node; first invalid key: "touchpad" (line -1, column -1)
```

I've tried deleting each part of my config, and even just deleting the entire contents, and I still get the error... But... Everything seems to be working?

I don't have a touchpad (YET! I'm getting one because of this software :) ) but I have this at the bottom of my config, just a leftover 'example' from when I was testing:

```

touchpad:
  speed:
    swipe_threshold: 15

  gestures:
    - type: pinch
      fingers: 2
      direction: in

      actions:
        - plasma_shortcut: kwin,Window Close
```

And if I remove that, I see the same error twice, and then nothing works any more.

So, I just leave that there for now and my stuff is working, but I thought I should report it.
