### ISSUE TITLE
Gesture groups

### ISSUE THREAD

**Issue by taj-ny** [taj-ny/InputActions#86]
Gesture groups would allow to add the same properties to many gestures, reducing duplication.

Example:
```yaml
touchpad:
  gestures:
    - type: swipe
      direction: left
      fingers: 3
      keyboard_modifiers: [ meta ]
      
      conditions:
        - window_class: firefox
      
      actions:
        - on: begin
          input:
            - mouse: [ back ]
            
    - type: swipe
      direction: right
      fingers: 3
      keyboard_modifiers: [ meta ]
      
      conditions:
        - window_class: firefox
      
      actions:
        - on: begin
          input:
            - mouse: [ forward ]
```
would become
```yaml
touchpad:
  gestures:
    - type: swipe
      fingers: 3
      keyboard_modifiers: [ meta ]

      conditions:
        - window_class: firefox
      
      gestures:
        - direction: left
          actions:
            - on: begin
              input:
                - mouse: [ back ]
                
        - direction: right
          actions:
            - on: begin
              input:
                - mouse: [ forward ]
```
