### ISSUE TITLE
Swipe gestures of direction "any" aren't recognized right away

### ISSUE THREAD

**Issue by Glampi42** [taj-ny/InputActions#96]
Consider the following gesture:
```
# move window / global
        - type: swipe
          fingers: 2
          direction: any

          keyboard_modifiers: [ meta ]

          actions:
            - on: begin
              input:
                - keyboard: [ +leftmeta ]
                - mouse: [ +left ]

            - on: update
              input:
                - mouse: [ move_by_delta ]

            - on: end_cancel
              input:
                - keyboard: [ -leftmeta ]
                - mouse: [ -left ]
```

If I press "meta" and begin dragging with two fingers strictly horizontally (angle 0°), then the window will move horizontally—however, if I then change the direction slightly (angle ~20°) to bring the window a bit higher on the screen, the window will still move strictly horizontally. It will only begin to move vertically after I change the direction of the swipe significantly enough (I assume ~45°) from the horizontal direction (I am describing a single stroke here, meaning I change the direction of the swipe while my fingers stay on the touchpad). After that, the window "snaps off" from the horizontal restriction of movement and can now move in any direction. The same happens when I begin the swipe vertically, but not if I begin the swipe diagonally.
I assume this is the case because the gesture direction is considered "left_right" if I swipe horizontally, "up_down" if I swipe vertically, and only becomes "any" when I swipe diagonally/change the swipe direction by a big angle. It would be nice if gestures like the one above would be considered "any" from the very beginning of the swipe, such that the window being dragged would follow the swipe direction without being restricted to only vertical/horizontal movement.
