### ISSUE TITLE
Better conditions and variables

### ISSUE THREAD

**Issue by taj-ny** [taj-ny/InputActions#99]
Variables will store various information and will be used primarily in conditions and actions. Each type will have a bunch of operators for comparisons. At some point there will be actions for managing custom variables.

Examples:
```yaml
conditions:
  all:
    - fingers >= 2
    - keyboard_modifiers == meta # "== [ meta ]" will work too
    - window_class == "firefox"
    - window_title matches " - YouTube$" # Per-website gestures, requires browser to put tab title in the window title
# ------
input:
  - mouse: [ scroll_x $delta_x ] # Support for math expression will eventually be added
# ------
command: /path/to/script.sh "$window_title"
```

Some variables I came up with:
- delta{_x,_y} (delta of the latest input event)
- finger_{number}_position (for touchpads and touchscreens)
- fingers (will replace *Gesture.fingers*)
- keyboard_modifiers (will replace *Gesture.keyboard_modifiers*)
- mouse_buttons (not sure about that one)
- pointer_position_screen (relative to current screen)
- pointer_position_window (relative to window the pointer is over)
- pointer_shape
- speed (will replace *Gesture.speed*)
- window_class
- window_fullscreen
- window_maximized
- window_title

Backwards compatibility will be kept. Suggest variables that may be useful for you here.
